services:
  order-db:
    image: postgres:16-alpine
    container_name: order-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - shop-network
    restart: unless-stopped

volumes:
  order-db-data:

networks:
  shop-network:
    external: true